//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trendyol.Core
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Configuration
    {
        /// <summary>
        /// Id
        /// </summary>
        [DataMember]
        public int Id { get; set; }
        /// <summary>
        /// Name
        /// </summary>
        [DataMember]
        public string Name { get; set; }
        /// <summary>
        /// Type
        /// </summary>
        [DataMember]
        public string Type { get; set; }
        /// <summary>
        /// Value
        /// </summary>
        [DataMember]
        public string Value { get; set; }
        /// <summary>
        /// IsActive
        /// </summary>
        [DataMember]
        public bool IsActive { get; set; }
        /// <summary>
        /// ApplicationName
        /// </summary>
        [DataMember]
        public string ApplicationName { get; set; }
    }
}
